apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
spec:
  values:
    security:
      selfSigned: false
    global:
      multiCluster:
        clusterName: istiomcsshared
      network: local
      meshNetworks:
        local:
          endpoints:
          - fromRegistry: Kubernetes
          gateways:
          - registry_service_name: istio-ingressgateway.istio-system.svc.cluster.local
            port: 443

        remote:
          endpoints:
          - fromRegistry: istioawsshared
          gateways:
          - registry_service_name: istio-ingressgateway.istio-system.svc.cluster.local
            port: 443

      meshExpansion:
        enabled: true
